version: '3.8'

services:
  leantime:
    image: leantime/leantime:latest
    restart: unless-stopped
    environment:
      # IMPORTANT: Set APP_URL to your actual domain in Coolify
      LEAN_APP_URL: '${APP_URL:-https://leantime.example.com}'
      LEAN_APP_DIR: '/var/www/html'
      LEAN_DEBUG: '${LEAN_DEBUG:-0}'
      
      # Database Configuration
      LEAN_DB_HOST: 'mysql'
      LEAN_DB_DATABASE: '${MYSQL_DATABASE:-leantime}'
      LEAN_DB_USER: '${MYSQL_USER:-leantime}'
      LEAN_DB_PASSWORD: '${MYSQL_PASSWORD:-changeme123}'
      
      # Session & Security - CHANGE THIS!
      LEAN_SESSION_PASSWORD: '${LEAN_SESSION_PASSWORD:-GWE43JIOPGEW8u902384i0gjwe8p}'
      LEAN_SESSION_EXPIRATION: '${LEAN_SESSION_EXPIRATION:-28800}'
      
      # Email Configuration
      LEAN_EMAIL_RETURN: '${LEAN_EMAIL_RETURN:-hello@example.com}'
      LEAN_EMAIL_USE_SMTP: '${LEAN_EMAIL_USE_SMTP:-false}'
      
      # Default Timezone
      LEAN_DEFAULT_TIMEZONE: '${LEAN_DEFAULT_TIMEZONE:-America/New_York}'
      
    volumes:
      - leantime_public_userfiles:/var/www/html/public/userfiles
      - leantime_userfiles:/var/www/html/userfiles
      - leantime_plugins:/var/www/html/app/Plugins
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-changeme123}'
      MYSQL_DATABASE: '${MYSQL_DATABASE:-leantime}'
      MYSQL_USER: '${MYSQL_USER:-leantime}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-changeme123}'
    volumes:
      - mysql_data:/var/lib/mysql
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]

volumes:
  mysql_data:
  leantime_public_userfiles:
  leantime_userfiles:
  leantime_plugins: